const characters = [{"name": "アレック・ハーディ", "work": "Broadchurch", "image": "images/alec-hardy.jpg"}, {"name": "クロウリー", "work": "Good Omens", "image": "images/crowley.jpg"}, {"name": "10代目ドクター", "work": "Doctor Who", "image": "images/tenth-doctor.jpg"}, {"name": "14代目ドクター", "work": "Doctor Who", "image": "images/fourteenth-doctor.jpg"}, {"name": "キルグレイヴ", "work": "Jessica Jones", "image": "images/kilgrave.jpg"}, {"name": "フィリアス・フォッグ", "work": "Around the World in 80 Days", "image": "images/phileas-fogg.jpg"}, {"name": "トニー・バディンガム", "work": "Rivals", "image": "images/tony-baddingham.jpg"}, {"name": "マクベス", "work": "Macbeth", "image": "images/macbeth.jpg"}, {"name": "リチャード二世", "work": "Richard II", "image": "images/richard-ii.jpg"}, {"name": "カサノヴァ", "work": "Casanova", "image": "images/casanova.jpg"}, {"name": "キャンベル・ベイン", "work": "Takin' Over the Asylum", "image": "images/campbell-bain.jpg"}, {"name": "ブレンダン・ブロック", "work": "Secret Smile", "image": "images/brendan-block.jpg"}, {"name": "ピーター・カーライル", "work": "Blackpool", "image": "images/peter-carlisle.jpg"}, {"name": "ピーター・ヴィンセント", "work": "Fright Night", "image": "images/peter-vincent.jpg"}, {"name": "ジェームズ・アーバー", "work": "The Decoy Bride", "image": "images/james-arber.jpg"}, {"name": "アーサー・エディントン", "work": "Einstein and Eddington", "image": "images/eddington.jpg"}, {"name": "デイヴ・タイラー", "work": "Single Father", "image": "images/dave-tiler.jpg"}, {"name": "エイデン・ホインズ", "work": "The Politician's Husband", "image": "images/aiden-hoynes.jpg"}, {"name": "エメット・カーヴァー", "work": "Gracepoint", "image": "images/emmett-carver.jpg"}, {"name": "ハリー・ワトリング", "work": "Inside Man", "image": "images/harry-watling.jpg"}, {"name": "デニス・ニルセン", "work": "Des", "image": "images/dennis-nilsen.jpg"}, {"name": "サイモン・イェーツ", "work": "There She Goes", "image": "images/simon-yates.jpg"}, {"name": "ハムレット", "work": "Hamlet", "image": "images/hamlet.jpg"}, {"name": "ドン・ジュアン", "work": "Don Juan in Soho", "image": "images/don-juan.jpg"}, {"name": "トム・ケンドリック", "work": "Deadwater Fell", "image": "images/tom-kendrick.jpg"}, {"name": "R.D.レイン", "work": "Mad to Be Normal", "image": "images/rd-laing.jpg"}, {"name": "ジョン・ノックス", "work": "Mary Queen of Scots", "image": "images/john-knox.jpg"}, {"name": "バーティ・クラウチ・Jr.", "work": "Harry Potter and the Goblet of Fire", "image": "images/barty-crouch-jr.jpg"}, {"name": "ジンジャー・リトルジョン", "work": "Bright Young Things", "image": "images/ginger-littlejohn.jpg"}, {"name": "ウィル・バートン", "work": "The Escape Artist", "image": "images/will-burton.jpg"}];
const state={pool:[],groups:[],groupIndex:0,winners:[],roundsDone:0,totalSteps:1,points:new Map(),unknown:new Set()};
const $=id=>document.getElementById(id);
function initials(name){return name.replace(/[・\s]/g,"").slice(0,2)}
function shuffle(a){const arr=[...a];for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');window.scrollTo({top:0,behavior:'instant'})}
function makeImg(c){return `<img src="${c.image}" alt="${c.name}" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'"><div class="fallback" style="display:none">${initials(c.name)}</div>`}
function renderHero(){$('member-count').textContent=`${characters.length}人から、あなたのTOP9を。`;const hero=$('hero-collage');characters.slice(0,9).forEach(c=>{const t=document.createElement('div');t.className='hero-tile';t.innerHTML=makeImg(c);hero.appendChild(t)})}
function estimateSteps(n){let total=0,cur=n;while(cur>9){total+=Math.ceil(cur/3);cur=Math.ceil(cur/3)}return Math.max(total,1)}
function start(){const pool=characters.map((c,i)=>({...c,id:i}));state.pool=shuffle(pool);state.points=new Map(pool.map(c=>[c.id,0]));state.unknown=new Set();state.roundsDone=0;state.totalSteps=estimateSteps(pool.length);beginRound();show('quiz')}
function beginRound(){state.groups=[];for(let i=0;i<state.pool.length;i+=3)state.groups.push(state.pool.slice(i,i+3));state.groupIndex=0;state.winners=[];renderGroup()}
function updateProgress(){const done=Math.min(state.roundsDone,state.totalSteps);const pct=Math.round(done/state.totalSteps*100);$('percent').textContent=`${pct}%`;$('bar').style.width=`${pct}%`}
function renderGroup(){updateProgress();const group=state.groups[state.groupIndex];if(!group)return endRound();const wrap=$('choices');wrap.innerHTML='';group.forEach(c=>{const card=document.createElement('article');card.className='choice';card.innerHTML=`<div>${makeImg(c)}</div><div class="choice-body"><div class="choice-name">${c.name}</div><div class="choice-work">${c.work}</div><button class="unknown-btn" type="button">知らない</button></div>`;card.addEventListener('click',e=>{if(e.target.classList.contains('unknown-btn'))return;choose(c)});card.querySelector('.unknown-btn').addEventListener('click',e=>{e.stopPropagation();state.unknown.add(c.id);card.style.opacity='.35';card.style.pointerEvents='none';const known=group.filter(x=>!state.unknown.has(x.id));if(known.length===1)choose(known[0]);if(known.length===0)nextGroup()});wrap.appendChild(card)})}
function choose(c){state.winners.push(c);state.points.set(c.id,(state.points.get(c.id)||0)+10);nextGroup()}
function nextGroup(){state.roundsDone++;state.groupIndex++;renderGroup()}
function endRound(){const uniq=[...new Map(state.winners.map(c=>[c.id,c])).values()];if(uniq.length<=9)return finish(uniq);state.pool=shuffle(uniq);beginRound()}
function finish(finalists){const ids=new Set(finalists.map(c=>c.id));const extras=characters.map((c,i)=>({...c,id:i})).filter(c=>!ids.has(c.id)&&!state.unknown.has(c.id)).sort((a,b)=>(state.points.get(b.id)||0)-(state.points.get(a.id)||0));const ranked=[...finalists,...extras].sort((a,b)=>(state.points.get(b.id)||0)-(state.points.get(a.id)||0)).slice(0,9);const wrap=$('ranking');wrap.innerHTML='';ranked.forEach((c,i)=>{const el=document.createElement('article');el.className='rank';el.innerHTML=`<div class="rank-badge">${i+1}</div>${makeImg(c)}<div class="rank-body"><div class="rank-name">${c.name}</div><div class="rank-work">${c.work}</div></div>`;wrap.appendChild(el)});show('result')}
$('skip-round').addEventListener('click',()=>nextGroup());$('start-btn').addEventListener('click',start);$('restart-btn').addEventListener('click',()=>show('home'));renderHero();